#!/bin/bash

# Converts front_end/ files into embedded C arrays + vfs_entry table.
# Reads TARGET_FILES, OUT_C_FILE, OUT_H_FILE from env.
# Run from the repo root.

set -e

: "${OUT_C_FILE:?}" "${OUT_H_FILE:?}"

mkdir -p "$(dirname "$OUT_C_FILE")"

# Split space-separated paths into array, strip front_end/ prefix
IFS=' ' read -ra RAW_PATHS <<< "$TARGET_FILES"
PATHS=()
SYMS=()
for p in "${RAW_PATHS[@]}"; do
	vfs_path="${p#front_end/}"
	sym="$(echo "$vfs_path" | tr './' '__')"
	PATHS+=("$vfs_path")
	SYMS+=("$sym")
done

COUNT=${#PATHS[@]}

# Stage gzip-compressed copies here; xxd reads from these instead of the
# originals, so the embedded bytes are already gzip-compressed. -n on
# gzip strips the original filename/timestamp from its header, so the
# compressed output is reproducible across builds/machines.
STAGE_DIR="$(dirname "$OUT_C_FILE")/gzip_stage"
mkdir -p "$STAGE_DIR"

# ---- C source ----
{
	printf "// Auto-generated by %s. Do not edit.\n" "$(basename "$0")"
	printf "#include \"%s\"\n\n" "$(basename "$OUT_H_FILE")"

	for ((i = 0; i < COUNT; i++)); do
		path="${PATHS[$i]}"
		sym="${SYMS[$i]}"
		gz_path="$STAGE_DIR/$sym.gz"
		gzip -9 -n -c --verbose "front_end/$path" > "$gz_path"
		printf "// %s (gzip -9)\n" "$path"
		xxd -n "$sym" -i "$gz_path"
		printf "\n"
	done

	# vfs_entry lookup table (terminated by null entry).
	# sizeof works because the arrays are fully defined above.
	printf "vfs_entry vfs_table[] = {\n"
	for ((i = 0; i < COUNT; i++)); do
		path="${PATHS[$i]}"
		sym="${SYMS[$i]}"
		printf "\t{ \"%s\", %s, sizeof %s },\n" "$path" "$sym" "$sym"
	done
	printf "\t{ 0, 0, 0 }\n};\n"
} > "$OUT_C_FILE"

# rm -rf "$STAGE_DIR"
echo "Wrote $OUT_C_FILE and $OUT_H_FILE" >&2
